name: Deploy-AWS-SAM-Application

on:
  push:
    branches:
      - main

env:
  TEMPLATE_FILE: template.yaml
  SAM_CLI_TELEMETRY: 0

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/aws-test-sam-actions-role
          aws-region: ap-northeast-1
          role-session-name: SamDeploy
      - run: sam build
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset